language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "fdlessard-github"
    token:
#      secure: "your_token_encrypted_with_travis_encrypt_tool"
      secure: "f4ce05629b9ebfa52aaa75e9b28dd8397483dc68"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'



mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io  -Dsonar.organization=fdlessard-github -Dsonar.login=fdlessard@github